import { test, skip, mock, assert } from "../../../../Common/testCommon.js";

import accountsManager from "./manager.js"
import firestoreManager from "../../../../FireStoreAPI/manager.js"

// firestoreから取得するテスト
test("firestore get document test", {only:true}, async (t) => {
    const document = await firestoreManager.getDocs("M_Request", [["documentId", "==", "MrLi9EteTBiAj9BXFTRt"]]);
    const get = await document.get();
    const actual = '{"valid":true,"statuses":[{"path":"AmazonAdsAPI/Reporting/SponsoredV3/create","status":"CREATE"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/status","status":"STATUS"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/download","status":"DOWNLOAD"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/translate","status":"TRANSLATE"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/save","status":"SAVE"}],"details":[{"path":"AmazonAdsAPI/Reporting/SponsoredV3/SponsoredBrands/campaigns/translater1","tag":"マージ用レポート","body":"{\\"name\\":\\"\\",\\"startDate\\":\\"\\",\\"endDate\\":\\"\\",\\"configuration\\":{\\"adProduct\\":\\"SPONSORED_BRANDS\\",\\"groupBy\\":[\\"campaign\\"],\\"columns\\":[\\"date\\",\\"campaignId\\",\\"addToCart\\",\\"addToCartClicks\\",\\"brandedSearches\\",\\"brandedSearchesClicks\\",\\"campaignBudgetAmount\\",\\"campaignBudgetCurrencyCode\\",\\"campaignBudgetType\\",\\"campaignName\\",\\"campaignStatus\\",\\"clicks\\",\\"cost\\",\\"costType\\",\\"detailPageViews\\",\\"detailPageViewsClicks\\",\\"impressions\\",\\"newToBrandDetailPageViews\\",\\"newToBrandDetailPageViewsClicks\\",\\"newToBrandPurchases\\",\\"newToBrandPurchasesClicks\\",\\"newToBrandSales\\",\\"newToBrandSalesClicks\\",\\"newToBrandUnitsSold\\",\\"newToBrandUnitsSoldClicks\\",\\"purchases\\",\\"purchasesClicks\\",\\"purchasesPromoted\\",\\"sales\\",\\"salesClicks\\",\\"salesPromoted\\",\\"topOfSearchImpressionShare\\",\\"unitsSold\\",\\"unitsSoldClicks\\",\\"video5SecondViews\\",\\"videoCompleteViews\\",\\"videoFirstQuartileViews\\",\\"videoMidpointViews\\",\\"videoThirdQuartileViews\\",\\"videoUnmutes\\",\\"viewableImpressions\\"],\\"reportTypeId\\":\\"sbCampaigns\\",\\"timeUnit\\":\\"DAILY\\",\\"format\\":\\"GZIP_JSON\\"}}","refName":"advertiser","settingsJSON":""}],"tag":"スポンサーブランド"}'
    //firestoreManager.
    assert.strictEqual(JSON.stringify(get.docs[0].data()), actual);
}, "");

// 環境にセット
test("call create test", async (t) => {
    const actual = '{"valid":true,"statuses":[{"path":"AmazonAdsAPI/Reporting/SponsoredV3/create","status":"CREATE"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/status","status":"STATUS"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/download","status":"DOWNLOAD"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/translate","status":"TRANSLATE"},{"path":"AmazonAdsAPI/Reporting/SponsoredV3/save","status":"SAVE"}],"details":[{"path":"AmazonAdsAPI/Reporting/SponsoredV3/SponsoredBrands/campaigns/translater1","tag":"マージ用レポート","body":"{\\"name\\":\\"\\",\\"startDate\\":\\"\\",\\"endDate\\":\\"\\",\\"configuration\\":{\\"adProduct\\":\\"SPONSORED_BRANDS\\",\\"groupBy\\":[\\"campaign\\"],\\"columns\\":[\\"date\\",\\"campaignId\\",\\"addToCart\\",\\"addToCartClicks\\",\\"brandedSearches\\",\\"brandedSearchesClicks\\",\\"campaignBudgetAmount\\",\\"campaignBudgetCurrencyCode\\",\\"campaignBudgetType\\",\\"campaignName\\",\\"campaignStatus\\",\\"clicks\\",\\"cost\\",\\"costType\\",\\"detailPageViews\\",\\"detailPageViewsClicks\\",\\"impressions\\",\\"newToBrandDetailPageViews\\",\\"newToBrandDetailPageViewsClicks\\",\\"newToBrandPurchases\\",\\"newToBrandPurchasesClicks\\",\\"newToBrandSales\\",\\"newToBrandSalesClicks\\",\\"newToBrandUnitsSold\\",\\"newToBrandUnitsSoldClicks\\",\\"purchases\\",\\"purchasesClicks\\",\\"purchasesPromoted\\",\\"sales\\",\\"salesClicks\\",\\"salesPromoted\\",\\"topOfSearchImpressionShare\\",\\"unitsSold\\",\\"unitsSoldClicks\\",\\"video5SecondViews\\",\\"videoCompleteViews\\",\\"videoFirstQuartileViews\\",\\"videoMidpointViews\\",\\"videoThirdQuartileViews\\",\\"videoUnmutes\\",\\"viewableImpressions\\"],\\"reportTypeId\\":\\"sbCampaigns\\",\\"timeUnit\\":\\"DAILY\\",\\"format\\":\\"GZIP_JSON\\"}}","refName":"advertiser","settingsJSON":""}],"tag":"スポンサーブランド"}'

}, "")
